# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en
permalink: /:year/:month/:day/:title/

include: ['_pages']

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]

paginate_path: "blog/page:num/"
paginate: 2
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Atomic Energy
description: Thoughts on a turbulent age
keywords: 'jekyll,theme,gem-based'
author:
  name: Avi Deitcher
  job_title:
  location:
  email:
  bio: |
    Avi Deitcher is a technology business consultant who lives to dramatically improve
    fast-moving and fast-growing companies. He writes regularly on this blog, and can be
    reached via <a href="https://www.facebook.com/AtomicConsulting">Facebook</a>,
    <a href="https://www.twitter.com/avideitcher">Twitter</a> and
    <a href="mailto:avi@atomicinc.com">avi@atomicinc.com</a>.
  avatar: http://1.gravatar.com/avatar/4e402c10702de9c58974b25fe0d99562?s=60&amp;d=mm&amp;r=g
  social_links:
    - name: facebook
      url: http://www.facebook.com/AtomicConsulting
    - name: linkedin
      url: http://linkedin.com/company/atomic-inc
    - name: twitter
      url: https://www.twitter.com/avideitcher
blog:
  footer_content: Atomic Energy | Thoughts on a turbulent age

summary: |
  <b>Atomic</b> provides high-value, rapid-turnaround technology business consulting services to owners, executives and managers.
  <i>Strategically</i>, we hone, target and perfect your product strategy, by ensuring it really works and is tested in the
  unforgiving real-world of the market. <i>Operationally</i>, we directly improve your profits and customer satisfaction by
  leveraging people, process and technology to measurably increase return for each dollar of investment.
  <b>Atomic</b> combines the broad market perspective, strong domain expertise and deep technology experience
  required to drive your business to higher levels of revenue, market share and profitability.
  <b>Atomic</b> is the adrenaline boost for your business.



disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

foobar: barfoo

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Successes
    url: /successes
  - title: Testimonials
    url: /testimonials
  - title: Categories
    url: /categories
  - title: Archive
    url: /archive/

header_image: http://blog.atomicinc.com/wp-content/uploads/2015/01/cropped-digital-earth-background2.jpg

paths:
  home: /
  about: /about
  categories: /categories/
